# Generated by Django 4.1.5 on 2023-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('forget_password_token', models.CharField(default='vsdfjsd558dsdfsr5rr', max_length=100)),
            ],
        ),
    ]
