# Generated by Django 4.1.5 on 2023-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0002_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='Device_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
