# Generated by Django 4.1.5 on 2023-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0003_complaints_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='imageproof',
            field=models.ImageField(blank='True', null=True, upload_to='images/'),
        ),
    ]
