# Generated by Django 4.1.5 on 2023-02-07 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0005_remove_complaints_imageproof_complaints_videoproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Id_Numbeer', models.CharField(blank=True, max_length=100)),
                ('Class', models.CharField(blank=True, max_length=50)),
                ('Description', models.TextField(default='no remarks')),
                ('Device_Name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('videoproof', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
